default LuneOS
label LuneOS
   kernel /Image
   fdt /imx8mp-mecha-comet.dtb
append console=tty1 console=ttymxc1,115200 earlycon=ec_imx6q,0x30890000,115200 root=PARTLABEL=luneos-rootfs rw rootwait LUNEOS_NO_OUTPUT_REDIRECT
